### ISSUE TITLE
restart comment count for each reviewer

### ISSUE THREAD

**Issue by pdparker** [conig/revise#10]
I think it would be nice to restart the comment counter for each editor/reviewer.

**Comment by conig** [comment]
I agree that would be a nice feature. I'd imagine we would need a counter name as an input.

E.g.

```
\reviewer{reviewer1}{label}{

}
````

We would also need to initialise the counters before they are used. Maybe something can be done at the pre/post-processor stage to get around this. A super ugly solution would just be to initialise reviewer 1 through 10 by default.

**Comment by pdparker** [comment]
\setcounter{C}{0} is the obvious choice. Maybe we can add to the cls to set the counter to 0 after each heading?

**Comment by conig** [comment]
Would that cause issues with cross-referencing? Potentially resetting the counter is more important than cross-referencing.

**Comment by conig** [comment]
> \setcounter{C}{0} is the obvious choice. Maybe we can add to the cls to set the counter to 0 after each heading?

Yes we could probably hide that in the section command without causing too much chaos.

**Comment by conig** [comment]
> Yes we could probably hide that in the section command without causing too much chaos.

Turns out this isn't a thing. For the meantime I have defined a new command in the header:
```
\newreviewer
```
which will manually reset the counter. I'll try to find a more elegant solution.

**Comment by conig** [comment]
With the latest version comment numbers will automatically be reset every time there is a level 1 header.
