### ISSUE TITLE
Dependency textreadr is not on CRAN anymore

### ISSUE THREAD

**Issue by cjvanlissa** [conig/revise#16]
Consequently, all integration tests fail with:

```
* checking package dependencies ... ERROR
Package required but not available: 'textreadr'
```

**Comment by cjvanlissa** [comment]
It would probably be fine to replace `textreadr` with `pdftools`, unless you need the OCR functionality that `textreadr` imports from `tesseract`?

**Comment by conig** [comment]
Yep this is fine, thanks for doing this.
