### ISSUE TITLE
Should we export a specific environment for storing manuscripts?

### ISSUE THREAD

**Issue by conig** [conig/revise#26]
@cjvanlissa I'm really enjoying the new functionality you've built where manuscripts are automatically cached and searched.

I was wondering about the edge-case where users want to remove a manuscript from the cache (maybe they loaded the wrong manuscript erroniously). Is there an easy way to find and wipe the correct env at the moment, or do they have to restart the R session?

One solution might be to export an environment specifically for this functionality where users can easily see what objects are in there, and remove objects as needed e.g., `revise::manuscript_locker`. Would you be in favour of such a change or do you have concerns?

**Comment by cjvanlissa** [comment]
I guess that could work, but that only makes sense for interactive sessions.. `revise` would mostly be used in code chunks in markdown documents and would be evaluated when knitted. I can add the function, but I don't think we should advertise it widely.

**Comment by conig** [comment]
Agreed, most will never need this one, no need to promote—but nice to show users under the hood and give some control.
