### ISSUE TITLE
Reviewer comment anchor links

### ISSUE THREAD

**Issue by pdparker** [conig/revise#5]
I am wondering if we auto add and populate link [anchors](https://www.overleaf.com/project/5d40b140a45bd72e21b11552) for the reviewerComment add-in?

**Comment by conig** [comment]
That project's private so can't follow the link, but would this just be a cross-reference system for reviewer comment numbers? Very keen for that!

**Comment by conig** [comment]
```
\newcounter{rComment}
\newcommand{\rcomm}[1]{\refstepcounter{rComment}\label{#1}\ref{#1}}


\RC{\underline{Comment \rcomm{c1}.}
\vspace{-0.1cm}

Test

  }


Some answer


\RC{\underline{Comment \rcomm{c2}.}
\vspace{-0.1cm}

Test

  }


See previous response to Comment \ref{c1}
```

The above code would work for crossreferncing but won't provide clickable links

![image](https://user-images.githubusercontent.com/12742211/128434095-11243aae-90d2-4975-9e97-328b2ea75570.png)

**Comment by pdparker** [comment]
This is nice. Could also integrate \hypertarget to use with \hyperlink in the hyperref package for clickable links? I have tried to get this to work but can't for some reason.

**Comment by conig** [comment]
I'm battling too with hyperlink. I think rmarkdown uses hyperlink for other things based on my quick reading so there could be a conflict. I'll keep looking for solutions, but the above would be doable if we can't come up with anything interactive.

**Comment by conig** [comment]
With the our own output style I've been able to hide a lot more of the latex. We now have a new reviewer comment command

```
\reviewer{label}{

Reviewer text

  }
```

Label must be filled in. I've updated the addin so it will automatically include a unique label following the scheme 'c#'.

E.g. 


```{=tex}
\reviewer{c2}{
Your paper is rubbish.
  }
```
You can now make a cross-references with the `\ref{label}` command.

e.g.
```
In our previous comment \ref{c1} we pointed out that we don't GAF.
```

Haven't worked out how to make these clickable yet.

**Comment by pdparker** [comment]
> This is nice. Could also integrate \hypertarget to use with \hyperlink in the hyperref package for clickable links? I have tried to get this to work but can't for some reason.

The issues with internal links seem to come from setting the class of the document to draft. Removing the class line from the YAML fixes the hyperref issues for me. Links still do not appear in color but do work.

**Comment by conig** [comment]
I could change the links to coloured with this in the header:
```
\hypersetup{
    colorlinks = true,
    urlcolor=black,
    linkcolor=cyan,
}
```
![image](https://user-images.githubusercontent.com/12742211/130536787-384d0895-498d-4417-a3ab-b3714c042bda.png)

But it also changes the original labels to coloured which is a pain.

![image](https://user-images.githubusercontent.com/12742211/130536807-a7596ebf-2496-4089-b1d4-910f6b7982ff.png)

**Comment by conig** [comment]
I have added two new commands to simplify crossreferencing
\comment and \Comment (the latter just capitalises the first letter).

You just put in the tag after it. E.g. 

```
Refer back to our response to \comment{psychometrics}.
```

At the moment crossrefencing breaks if you reset the counters.

**Comment by pdparker** [comment]
In relation to target color, you could just use an empty \hypertarget like `\hypertarget{c1}{}`

**Comment by conig** [comment]
I had trouble amending my existing counter system so have rewritten. This appears to be working fine now when draft is turned off. Let me know if any issues.

links will be automatically generated with these tags:
```
\comment{tag}
\Comment{tag}
```
