### ISSUE TITLE
get_revision escaping $ leading to formula failure

### ISSUE THREAD

**Issue by pdparker** [conig/revise#7]
When a chunk has a formula, get_revision seems to escape $ signs e.g. from the knited tex file:

`\$\$

\beta = B \times \frac{SD_x}{IQR_y}

\$\$`

**Comment by conig** [comment]
I can't replicate this one:

From my manuscript:
```
<span id = "form">

$$beta = B \times \frac{SD_x}{IQR_y}$$

</span>
```

From my letter:

`r get_revision("form")`

Output:

![image](https://user-images.githubusercontent.com/12742211/128462732-21321d0b-2835-47f0-b1b2-19286344f8d8.png)

**Comment by conig** [comment]
I did note separating the $$ from the formula caused issues in the papaja letter. That may be the issue, can you just do it all on the one line?
