### ISSUE TITLE
better error handling for get_revision

### ISSUE THREAD

**Issue by pdparker** [conig/revise#8]
I think it would be good to have some more informative error messages for get_revision. I think the most critical is get_revision should check is target %in% names(manuscript$sections) or something similar?

**Comment by conig** [comment]
Amazingly I just added that this morning:

```
> get_revision("dependcor")
Error: Couldn't find a section in the manuscript tagged as 'dependcor'. Did you mean: dependcorr?
```

**Comment by pdparker** [comment]
great minds
