### ISSUE TITLE
include warning about Rstudio visual editor?

### ISSUE THREAD

**Issue by pdparker** [conig/revise#9]
the visual editor really screws up the add-ins and often the md tagging. So sick of seeing {\#}

**Comment by conig** [comment]
Yeah that's annoying. You should get this warning in the latest verison:

![image](https://user-images.githubusercontent.com/12742211/128981834-d1700686-4460-4372-b398-c7c13dad27a0.png)

It could trigger inappropriately as I'm looking to see whether context is empty or set to the console which appears to be what's causing the bug. Not sure if there is a better way to check whether in visual editor mode. But this should be appropriate in most cases.

**Comment by conig** [comment]
I improved this warning. It was trigging on empty scripts which I didn't want. Now it checks to see whether a selection exists. When it doesn't it triggers the warning. I don't think this should misfire.
